---
- name: Create Mongodb Group
  group:
    name: "{{ mongodb_user }}"
    gid: "{{ mongodb_gid }}"
    state: present
  tags: [mongodb, mongodb-configure]

- name: Create Mongodb User
  user:
    name: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    uid: "{{ mongodb_uid }}"
    state: present
  tags: [mongodb, mongodb-configure]

- name: Create KeyFile
  copy:
    dest: "{{ mongodb_security_keyfile }}"
    content: "{{ mongodb_keyfile_content }}"
    owner: "{{ mongodb_user }}"
    group: "root"
    mode: 0400
  when: mongodb_replication_enabled
  tags: [mongodb, mongodb-configure]

- name: Create Log Directory if Missing
  file:
    state: directory
    dest: "{{ mongodb_systemlog_path|dirname }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    mode: 0755
  when: mongodb_systemlog_destination == "file"
  tags: [mongodb, mongodb-configure]

- name: Check That Logfile Exists
  stat: path={{ mongodb_systemlog_path }}
  register: logfile_stat
  when: mongodb_systemlog_destination == "file"
  tags: [mongodb, mongodb-configure]

- name: Create Logfile if Missing
  file:
    state: touch
    dest: "{{ mongodb_systemlog_path }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    mode: 0644
  when: ( mongodb_systemlog_destination == "file"
        and logfile_stat is defined
        and not logfile_stat.stat.exists )
  tags: [mongodb, mongodb-configure]

- name: Ensure Dbpath Directory Exists
  file:
    path: "{{ mongodb_storage_dbpath }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    setype: 'mongod_var_lib_t'
    recurse: true
    follow: true
  tags: [mongodb, mongodb-configure]

- name: Configure Mongodb
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Mongodb Systemd Service
    - Wait when Mongodb is Started
  tags: [mongodb, mongodb-configure]

- name: Add Systemd Configuration if Present
  template:
    src: mongodb.service.j2
    dest: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_service_mgr == "systemd"
    - mongodb_manage_systemd_unit
  notify:
    - Systemd Daemon Reload
    - Restart Mongodb Systemd Service
    - Wait when Mongodb is Started
  tags: [mongodb, mongodb-configure]

- name: Enable MongoDB Service
  systemd:
    name: "{{ mongodb_daemon_name }}.service"
    enabled: true
  when:
    - ansible_service_mgr == "systemd"
    - mongodb_manage_systemd_unit
  notify:
    - Systemd Daemon Reload
    - Restart Mongodb Systemd Service
    - Wait when Mongodb is Started
  tags: [mongodb, mongodb-configure]

- name: Flush All Handlers at This Point
  meta: flush_handlers
  tags: [mongodb, mongodb-configure]
