---

- name: Configure a Replicaset '{{ mongodb_replication_replset }}'
  any_errors_fatal: true
  community.mongodb.mongodb_replicaset:
    login_user: "{{ (not mongodb_root_admin_exist.failed) | ternary(mongodb_root_admin_name, omit) }}"
    login_password: "{{ (not mongodb_root_admin_exist.failed) | ternary(mongodb_root_admin_password, omit) }}"
    login_host: "localhost"
    login_port: "{{ mongodb_net_port }}"
    login_database: "{{ mongodb_login_database }}"
    replica_set: "{{ mongodb_replication_replset }}"
    ssl: "{{ (mongodb_net_ssl_enabled and mongodb_net_ssl_mode == 'requireSSL') | ternary(true, false) }}"
    reconfigure: "{{ (mongodb_replication_reconfigure and not mongodb_root_admin_exist.failed) | ternary(mongodb_replication_reconfigure, false) }}"
    force: true
    members: "{{ groups.mongo_cluster | join(':' + mongodb_net_port | string + ',') }}"
    arbiter_at_index: "{{ groups.mongo_cluster.index(mongodb_arbiter_index) if mongodb_arbiter_index is defined else omit }}"
  tags: [mongodb, mongodb-replicaset]

- name: Waiting for the Replicaset '{{ mongodb_replication_replset }}' to Stabilise
  any_errors_fatal: true
  community.mongodb.mongodb_status:
    login_user: "{{ (not mongodb_root_admin_exist.failed) | ternary(mongodb_root_admin_name, omit) }}"
    login_password: "{{ (not mongodb_root_admin_exist.failed) | ternary(mongodb_root_admin_password, omit) }}"
    login_host: "localhost"
    login_port: "{{ mongodb_net_port }}"
    login_database: "{{ mongodb_login_database }}"
    replica_set: "{{ mongodb_replication_replset }}"
    ssl: "{{ (mongodb_net_ssl_enabled and mongodb_net_ssl_mode == 'requireSSL') | ternary(true, false) }}"
    poll: 10
    interval: 10
  register: mongodb_replicaset_status
  tags: [mongodb, mongodb-replicaset]
