---

- name: Set ansible_distribution_release to Buster (Debian 10) when Bullseye (Debian 11)
  set_fact:
    ansible_distribution_release: "buster"
  when: ansible_distribution_release == "bullseye"
  tags: [mongodb, mongodb-install, mongodb-uninstall]

- name: Include OS-specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: [mongodb, mongodb-install, mongodb-uninstall]

- name: Include Validation Tasks
  include_tasks: "validate.yml"
  tags: [mongodb, mongodb-configure, mongodb-replicaset, mongodb-create-admin-users, mongodb-create-oplog-users, mongodb-add-users, mongodb-exporter]

- name: Include Mongo and Mongodb-Exporter Remove Tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "uninstall.{{ ansible_distribution_release | lower }}.yml"
    - "uninstall.{{ ansible_distribution | lower }}.yml"
    - "uninstall.{{ ansible_os_family | lower }}.yml"
  tags: [never, mongodb-uninstall, mongodb-uninstall-exporter, mongodb-dbdelete]

- name: Include Installation Tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "install.{{ ansible_distribution | lower }}.yml"
    - "install.{{ ansible_os_family | lower }}.yml"
  tags: [mongodb, mongodb-install]

- name: Include Configuration Tasks
  include_tasks: configure_mongodb.yml
  tags: [mongodb, mongodb-configure]

- name: Set Index of Arbiter in Hosts File
  set_fact: 
    mongodb_arbiter: "{{ (hostvars|dictsort|selectattr('1.mongodb_arbiter', 'defined')|map(attribute='1.inventory_hostname')|list)[0] }}"
  when:
    - mongodb_replication_enabled
    - (hostvars|dictsort|selectattr('1.mongodb_arbiter', 'defined')|map(attribute='1.inventory_hostname')|list)[0] is defined
  tags: [mongodb, mongodb-replicaset]

- name: Include Replication Tasks for Master
  include_tasks: create_replicaset.yml
  when:
    - mongodb_replication_enabled
    - mongodb_master is defined
    - mongodb_master
  tags: [mongodb, mongodb-replicaset]

- name: "Include Users Creation Tasks{% if mongodb_replication_enabled %} for Master{% endif %}"
  include_tasks: create_users.yml
  when: (mongodb_replication_enabled and mongodb_master is defined and mongodb_master) or
        not mongodb_replication_enabled
  # no_log: true
  tags: [mongodb, mongodb-create-admin-users, mongodb-create-oplog-users, mongodb-add-users]

- name: Include MMS Agent Configuration
  include_tasks: mms-agent.yml
  when: mongodb_mms_api_key | length > 0
  tags: [mongodb, mongodb-mms]

- name: Include Node-Exporter Installation Tasks
  include_tasks: mongodb-exporter.yaml
  when: mongodb_exporter_enabled == 'true'
  tags: [mongodb, mongodb-exporter]
