---

- name: Systemd Daemon Reload
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: Restart Mongodb Systemd Service
  systemd:
    name: "{{ mongodb_daemon_name }}"
    state: restarted
    enabled: true
  when: ansible_service_mgr == "systemd"

- name: Restart Mongodb Service
  service:
    name: "{{ mongodb_daemon_name }}"
    state: restarted
    enabled: true
  when: ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'service'

- name: Wait when Mongodb is Started
  wait_for:
    host: "{{ item }}"
    port: "{{ mongodb_net_port }}"
    timeout: 120
    delay: 10
  with_items: "{{ mongodb_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list }}"

- name: Restart Mongodb MMS Monitoring Agent
  service:
    name: mongodb-mms-monitoring-agent
    state: restarted

- name: Restart Mongodb-Exporter
  systemd:
    name: mongodb-exporter
    daemon_reload: true
    state: restarted
  when: ansible_service_mgr == "systemd"
