---

- name: Restart Mongos Systemd Service
  systemd:
    name: "{{ mongos_daemon_name }}"
    state: "restarted"
    enabled: true
  when:
    - ansible_service_mgr == "systemd"
    - mongodb_main_group == mongos_host_group
  tags: [never, mongos-force-restart]

- name: Restart Mongos Init Service
  service:
    name: "{{ mongos_daemon_name }}"
    state: "restarted"
    enabled: true
  when:
    - ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'service'
    - mongodb_main_group == mongos_host_group
  tags: [never, mongos-force-restart]

- name: Wait When Mongos is Started
  wait_for:
    host: "{{ _mongos_net_bindip_item }}"
    port: "{{ mongos_net_port }}"
    timeout: 60
  with_items: "{{ mongos_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list }}"
  loop_control:
    loop_var: _mongos_net_bindip_item
  when:
    - mongodb_main_group == mongos_host_group
  tags: [never, mongos-force-restart]
