---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - &debian
    image: "debian:bullseye"
    dockerfile: Dockerfile.j2
    docker_networks:
      - name: test_docker_network
        ipam_config:
          - subnet: 10.172.0.0/24
            gateway: 10.172.0.1
    pre_build_image: false
    privileged: true
    required: true
    # command: ""
    capabilities:
      - SYS_ADMIN
    cgroup_parent: "docker.slice"
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    exposed_ports:
      - 27017/tcp
      - 27018/tcp
      - 27019/tcp
      - 27020/tcp
      - 9216/tcp
    groups:
      - mongo_cluster
    name: mongo01
    hostname: mongo01
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.10

  - <<: *debian
    name: mongo02
    hostname: mongo02
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.11

  - <<: *debian
    name: mongo03
    hostname: mongo03
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.12

provisioner:
  log: true
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: False
      timeout: 60
  connection_options:
    ansible_ssh_user: root
    ansible_become: False
  inventory:
    links:
      group_vars: ../../tests/group_vars/
      #host_vars: ../../inventory/host_vars/
      hosts: ../../tests/hosts-cluster
  #converge: ../../tests/test.yml
  playbooks:
    prepare: prepare.yml

verifier:
  name: ansible
