---

- name: Check
  hosts: mongo_cluster
  gather_facts: false
  tasks:
    - name: Ping
      ping:


# - name: Preparing MongoDB for tests
#   hosts: mongo_cluster
#   gather_facts: no
#   tasks:
#     - name: "Add Hostnames to /etc/hosts"
#       raw: |
#         sudo apt update
#         sudo apt install python3
#         sudo bash -c 'cat <<EOF >> /etc/hosts
#         172.17.0.2 host1
#         172.17.0.3 host2
#         172.17.0.4 host3
#         EOF'

#     - name: "Check systemctl"
#       shell: systemctl

    # - name: Install Python3
    #   raw: |
    #     sudo apt update
    #     sudo apt install python3
    #   when: ansible_os_family == 'Debian'

    # - name: Install Python3
    #   yum:
    #     update_cache: true
    #     name:
    #       - python3
    #   when: ansible_os_family == 'RedHat'

    # - name: Install prerequisite packages for molecule testing on Debian or Ubuntu >= 18
    #   apt:
    #     update_cache: true
    #     name:
    #       - gpg
    #       - dirmngr
    #   when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 18) or ansible_distribution == 'Debian'
